### ISSUE TITLE
Line by line?

### ISSUE THREAD

**Issue by huschai** [votum/jquery.equalheight#1]
A great enhancement would be, if the equal-height would work line by line, so each row could have its own equal height. #morecomplexityrules

**Comment by feeela** [comment]
This is already supported through using the `data-equal-height` property with different values per line.
Example:

``` html
<div data-equalheight-wrapper>
    <div class="line1">
        <div data-equal-height="1">some content</div>
        <div data-equal-height="1">some content</div>
    </div>
    <div class="line2">
        <div data-equal-height="2">some content</div>
        <div data-equal-height="2">some content</div>
    </div>
</div>
```

You may add those values using JS before loading the equal height script. This depends on the definition of a "line" in your layout.

#lesscomplexityrules ;-)
